language: php

php:
  - 7.0
  - 7.1
  - 7.2

sudo: false

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

install:
  - composer install --no-interaction --prefer-dist

script:
  - vendor/bin/phpunit --coverage-clover clover.xml

after_script:
  - ./cc-test-reporter format-coverage -t clover -o codeclimate.json
  - ./cc-test-reporter upload-coverage -i codeclimate.json

notifications:
  email: false
